---
- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install common packages
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
      - python3-pip
      - software-properties-common
      - ufw
    state: present

- name: Set timezone
  timezone:
    name: UTC

- name: Configure UFW
  ufw:
    state: enabled
    policy: deny
    rule: allow
    port: 22
    proto: tcp
