---
- name: Enable IP forwarding
  sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    state: present
    reload: yes

- name: Set up NAT for internal hosts
  iptables:
    table: nat
    chain: POSTROUTING
    source: 10.0.0.0/16
    jump: MASQUERADE
    state: present

- name: Save iptables rules
  shell: |
    iptables-save > /etc/iptables.rules
    ip6tables-save > /etc/ip6tables.rules
  args:
    executable: /bin/bash

- name: Create iptables restore service
  copy:
    dest: /etc/systemd/system/iptables-restore.service
    content: |
      [Unit]
      Description=Restore iptables rules
      Before=network-pre.target
      Wants=network-pre.target

      [Service]
      Type=oneshot
      ExecStart=/sbin/iptables-restore /etc/iptables.rules
      ExecStart=/sbin/ip6tables-restore /etc/ip6tables.rules
      RemainAfterExit=yes

      [Install]
      WantedBy=multi-user.target

- name: Enable iptables restore service
  systemd:
    name: iptables-restore
    enabled: yes
    daemon_reload: yes

- name: Allow SSH access
  ufw:
    rule: allow
    port: 22
    proto: tcp
